<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


	<PropertyGroup>
	  <Version>1.0.0</Version>

	  <!-- Keep AssemblyVersion stable unless MAJOR changes -->
	  <AssemblyVersion>1.0.0.0</AssemblyVersion>

	  <P4_CHANGELIST Condition="'$(P4_CHANGELIST)' == ''">0</P4_CHANGELIST>
 
	  <!-- Use Perforce changelist as build number -->
	  <FileVersion>1.0.0.$([MSBuild]::Modulo($(P4_CHANGELIST), 65535))</FileVersion>

	  <InformationalVersion>
		1.0.0+cl.$(P4_CHANGELIST)
	  </InformationalVersion>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="9.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.2" />
    <PackageReference Include="System.Collections.Immutable" Version="10.0.7" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DataBase\" />
  </ItemGroup>

</Project>
